### ISSUE TITLE
First Login Failed

### ISSUE THREAD

**Issue by Subways-Sun** [JPyke3/mbp-manjaro#10]
Thank you for creating this! I’ve followed steps and got Manjaro installed. When I boot it, the login screen shows, but after I entered my password, the screen goes black. A while later, the fan ramps up and it shuts itself down. Would you please help me on that?

Device: MBP 2019 16-inch (MacBookPro16,1)

**Comment by JPyke3** [comment]
No problem! A few things to help me out:
1) Would you be able to help me out with which edition you are using? What is your desktop environment?
2) What kernel version did you install? Linux57?
3) Would you be able to post the output of `journalctl -r -b -1` after a crash? 

To me it sounds like something that starts when your desktop environment starts is causing a kernel panic/crashing the system. Have you installed anything after isntalling Manjaro?

**Comment by Subways-Sun** [comment]
Hi I am using Linux 57 Gnome edition, and I’m not sure about the desktop environment (don’t know how to change or check that). I am not able to enter the Linux OS (or is there a way to fire up terminal without entering the desktop?)

I ended up trying the journalctl command in my Linux Live USB and yielded “Specifying boot ID or boot offset has no effect, no persistent journal was found.”

**Comment by JPyke3** [comment]
Hi, all good Gnome is your desktop environment :)

> I am not able to enter the Linux OS (or is there a way to fire up terminal without entering the desktop?)

Yes you can fire up a terminal on the login screen by pressing control alt and f1-f9, `control alt f2` would be what you use as `control alt f1` is used for Gnome.
> I ended up trying the journalctl command in my Linux Live USB and yielded “Specifying boot ID or boot offset has no effect, no persistent journal was found.”

Okay no worries, try entering another terminal session using `control alt f2` and try the Journalctl command again.

Sorry it took so long to get back to you some other things caught up to me. Let me know how you get on :)

**Comment by JPyke3** [comment]
I'm going to go ahead and close this one for now. Let me know if there are any updates :)

**Comment by Subways-Sun** [comment]
Hi! Sorry it's been long, I haven't had time to go over these stuff. I have managed to get the output of journalctl -r -b -1, it's attached in the file. If anything else is required to diagnose the problem. please let me know! Thanks a lot!!!
[journalctl_output.txt](https://github.com/JPyke3/mbp-manjaro/files/5397485/journalctl_output.txt)

**Comment by dominalien** [comment]
I have the exact same problem, also on MBP 16,1. Manjaro installs OK, but on reboot it crashes on login. I'm attaching my journalctl output. 13:12:19 is the moment I press enter after putting in the password.
[crash.log](https://github.com/JPyke3/mbp-manjaro/files/6215658/crash.log)
