### ISSUE TITLE
Error in building iso for KDE

### ISSUE THREAD

**Issue by arorasarthak** [JPyke3/mbp-manjaro#2]
Thank you so much for this amazing repo! 

I was just trying to follow the steps in the ["Building for yourself"](https://github.com/JPyke3/mbp-manjaro#building-for-yourself) section of the readme for KDE, but it stops after synchronizing package databases and throws an error. Here's my terminal output:

```
buildiso -f -p kde -k linux56-mbp
 --> Profile: [kde]
==> Start building [kde]
==> Cleaning up ...
  -> Deleting chroot [rootfs] (x86_64) ...
  -> Deleting isoroot [iso] ...
 --> Loading Packages: [Packages-Root] ...
==> Prepare [Base installation] (rootfs)
 --> mirror: https://manjaro.moson.eu/stable/$repo/$arch
==> Creating install root at /var/lib/manjaro-tools/buildiso/kde/x86_64/rootfs
  -> Installing packages to /var/lib/manjaro-tools/buildiso/kde/x86_64/rootfs
:: Synchronizing package databases...
 core                                170.1 KiB  2.91 MiB/s 00:00 [###################################] 100%
 extra                                 2.0 MiB  2.87 MiB/s 00:01 [###################################] 100%
 community                             5.9 MiB  3.29 MiB/s 00:02 [###################################] 100%
 multilib                            195.2 KiB  3.34 MiB/s 00:00 [###################################] 100%
error: target not found: linux56-mbp
==> ERROR: Failed to install packages to new root
==> ERROR: Failed to install all packages
```
I tried compiling with xfce, i3 and gnome and they are working perfectly with the newly added touchbar + audio packages!

All of the above was done inside virtual box with a manjaro-xfce iso downloaded from the [releases](https://github.com/JPyke3/mbp-manjaro#releases) section. I also noticed that the KDE folder in drive doesn't have an iso image. Is there something that I am missing during the KDE iso build procedure?

**Comment by JPyke3** [comment]
Ahhhhh yep. Good catch! Was a bit of an oversight of my part, forgot to add the custom repository to the KDE edition. Thanks for that one!

Try re-cloning the repo. Master branch now has the changes to KDE (See 11853bdf9e5c60c47702f7aab15cdeee05c83efc). I gave it a small test and works just fine on my end :)

**Comment by arorasarthak** [comment]
Just ran a fresh compile. Tested the live cd and it works!

Thanks!
