### ISSUE TITLE
Manjaro Deepin login loop, Doesn't login.

### ISSUE THREAD

**Issue by Jiya-Ull-Haq** [JPyke3/mbp-manjaro#23]
- **Mac Model:** MacBook Air 2019, 13"

- **Issue:** Manjaro Deepin doesn't log in.

- **Steps I've followed:**
1. Installed Manjaro Deepin iso
2. Created a Bootable drive 
3. Booted into drive
4. Clicked Boot x86 64 
5. Took a while
6. Login Screen appeared
7. Tried to log in using the password "manjaro"
8. flashes some other screen and again goes into Login screen.
9. Again if I try to enter the password it does the same. 

**Screenshots:**
- Login Screen
![IMG_1BA4D8483096-1](https://user-images.githubusercontent.com/60106386/128563489-f00a5c07-880c-4d28-8cdf-0bd44e5a7419.jpeg)

- Screen which flashes
![IMG_4317](https://user-images.githubusercontent.com/60106386/128562592-9ec97684-1202-47e6-8f6e-bb2c62bcb61c.PNG)

**Comment by AdityaGarg8** [comment]
This seema to be issue with the desktop environment. You may try another release like KDE.
