### ISSUE TITLE
Suspend broken

### ISSUE THREAD

**Issue by Whyhow314** [JPyke3/mbp-manjaro#6]
I followed the instructions with several linked ISOs on my Macbook pro 15,2 (with gnome 5.6 and 5.7, kde 5.6, xfce 5.6) and while it seems to mostly work fine, it stops responding to the built-in keyboard and trackpad when I suspend, and usually crashes shortly after.

**Comment by JPyke3** [comment]
Hi, thank you for the report. I am in fact aware with the suspend being broken and I am debugging this at the moment. I saw in our Discord channel someone had a userspace fix to this issue https://discordapp.com/channels/595304521857630254/596303447033249822/754403964610543627. However, I plan on working on this from the kernel side to see what we can do.

**Comment by JPyke3** [comment]
Going to close this issue here, as it isn't related to the images themselves and more to the Kernel. Follow the issue here: https://github.com/JPyke3/mbp-manjaro-kernel/issues/7#issue-703291135
