### ISSUE TITLE
I followed every instructions but manjaro isn’t listed in the boot menu

### ISSUE THREAD

**Issue by Wes974** [JPyke3/mbp-manjaro#9]
Hi ! I followed all of the instructions with no issue but after completing the installation after rebooting when I press Option while powering on, Manjaro isn't listed.
I installed Linux57 manjaro i3 on a MacBook Pro 16".

**Comment by JPyke3** [comment]
Hi, my guess is, is that you haven't run the `bootctl` command whilst chrooted into the system.

To fix this, launch the iso again, open a terminal and mount the root partition on `/mnt` and the boot partition on `/mnt/boot` then run `manjaro-chroot /mnt` and run `bootctl --path=/boot --no-variables install` again, after that unmount the partitions and reboot, see if that fixes the issue. 

If that doesn't work ensure the file `/boot/loader/entries/manjaro.conf` exists.

Let me know how you get on 👍

**Comment by Wes974** [comment]
I had already typed these commands because I followed every instructions of the readme. I tried to launch these commands again but I still can't see manjaro when pressing Option when booting. Do you know where it might come from ?

**Comment by JPyke3** [comment]
Yes it seems like `systemd-boot` hasn't correctly installed.

Would you be able to tell me the output of `fdisk -l` on the liveusb.

as well as mounting the `/dev/nvme0n1p1` partition to `/mnt` and doing a ls of `/mnt` and `/mnt/boot/EFI/BOOT`, then posting the results here :)

**Comment by Wes974** [comment]
Output of `sudo fdisk -l`:

```
[manjaro@manjaro-i3 ~]$ sudo fdisk -l
Disk /dev/nvme0n1: 931.84 GiB, 1000555581440 bytes, 244276265 sectors
Disk model: APPLE SSD AP1024N                       
Units: sectors of 1 * 4096 = 4096 bytes
Sector size (logical/physical): 4096 bytes / 4096 bytes
I/O size (minimum/optimal): 4096 bytes / 4096 bytes
Disklabel type: gpt
Disk identifier: 56B84521-C3A7-4852-9526-D2AA15F48A7B

Device             Start       End   Sectors   Size Type
/dev/nvme0n1p1         6     76805     76800   300M EFI System
/dev/nvme0n1p2     76806 205154920 205078115 782.3G Apple APFS
/dev/nvme0n1p3 205154921 218263551  13108631    50G Linux filesystem
/dev/nvme0n1p4 229569024 244140027  14571004  55.6G Microsoft basic data
/dev/nvme0n1p5 244140032 244275967    135936   531M Windows recovery environment
/dev/nvme0n1p6 218263552 229569023  11305472  43.1G Linux filesystem

Partition table entries are not in disk order.


Disk /dev/loop0: 94.2 MiB, 98779136 bytes, 192928 sectors
Units: sectors of 1 * 512 = 512 bytes
Sector size (logical/physical): 512 bytes / 512 bytes
I/O size (minimum/optimal): 512 bytes / 512 bytes


Disk /dev/loop1: 109.26 MiB, 114565120 bytes, 223760 sectors
Units: sectors of 1 * 512 = 512 bytes
Sector size (logical/physical): 512 bytes / 512 bytes
I/O size (minimum/optimal): 512 bytes / 512 bytes


Disk /dev/loop2: 1009.99 MiB, 1059049472 bytes, 2068456 sectors
Units: sectors of 1 * 512 = 512 bytes
Sector size (logical/physical): 512 bytes / 512 bytes
I/O size (minimum/optimal): 512 bytes / 512 bytes


Disk /dev/loop3: 750.43 MiB, 786878464 bytes, 1536872 sectors
Units: sectors of 1 * 512 = 512 bytes
Sector size (logical/physical): 512 bytes / 512 bytes
I/O size (minimum/optimal): 512 bytes / 512 bytes


Disk /dev/sda: 57.3 GiB, 61530439680 bytes, 120176640 sectors
Disk model: Dual Drive      
Units: sectors of 1 * 512 = 512 bytes
Sector size (logical/physical): 512 bytes / 512 bytes
I/O size (minimum/optimal): 512 bytes / 512 bytes
Disklabel type: dos
Disk identifier: 0x00000000

Device     Boot   Start     End Sectors Size Id Type
/dev/sda1  *         64 4155071 4155008   2G  0 Empty
/dev/sda2       4155072 4163263    8192   4M ef EFI (FAT-12/16/32)
```
ls of `/mnt`:

```
[manjaro@manjaro-i3 ~]$ ls /mnt
EFI                                    initramfs-5.7-x86_64-mbp.img  memtest86+
c4ffa0ce15264e9b96f586649e1ab337       intel-ucode.img               vmlinuz-5.7-x86_64-mbp
grub                                   linux57-mbp-x86_64.kver
initramfs-5.7-x86_64-mbp-fallback.img  loader
```

ls of `/mnt/EFI` and of `/mnt/EFI/Boot`:

```
[manjaro@manjaro-i3 ~]$ ls /mnt/EFI/
APPLE/     Boot/      Linux/     Microsoft/ systemd/   
[manjaro@manjaro-i3 ~]$ ls /mnt/EFI/Boot/
bootx64.efi
```

**Comment by JPyke3** [comment]
Hm interesting, everything seems to be in place there. Do you have an image of what it does look like when you hold option and get to the Apple boot menu?

**Comment by Wes974** [comment]
![image](https://user-images.githubusercontent.com/7169107/94414218-9c479f00-016b-11eb-9b54-0f1c5fa9cecf.jpeg)

**Comment by Wes974** [comment]
Oh I've just noticed something, if I boot into Windows I get this and can boot into Windows ![image](https://user-images.githubusercontent.com/7169107/94414333-c26d3f00-016b-11eb-9e28-b92ad8de4ab6.jpeg)

**Comment by JPyke3** [comment]
Oh so it looks like `systemd-boot` and the windows boot manager use the same `.efi` directory, do both of the options work? Can you boot to windows with the Windows option and to Manjaro with the manjaro option?

**Comment by Wes974** [comment]
Yes both options works, I can successfully boot into Manjaro and into Windows

**Comment by JPyke3** [comment]
Okay great then I will close this one and update the README tomorrow about this quirk

**Comment by Wes974** [comment]
Great ! Thanks for your help and for your work !

**Comment by JPyke3** [comment]
Added to the faq in 2106e5f1306d1ebc123d7c78d62f3135a34e0f16.
